apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: codgen-release010-test 
  janus-idp.io/tekton: codgen-release010-test
  backstage.io/kubernetes-id: codgen-release010-test
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: codgen-release010-test
resources: 
- application-dev.yaml